name: Weather workflow

on: push

jobs:
  test:
    name: Test code with flake8
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install flake8==7.0.0 flake8-isort==6.0.0 flake8-broken-line==1.0.0 pep8-naming==0.13.3
    - name: Test code
      run: python -m flake8 src/